### ISSUE TITLE
Avatar url error

### ISSUE THREAD

**Issue by brddev** [Gusarovv/discord-card-canvas#86]
```Error: Error loading the avatar image. The URL may be invalid.```
The url is crt i have consoled it but problem with package

Here it is whole error  
```Error: Error loading the avatar image. The URL may be invalid.
    at RankCardBuilder.draw (/home/container/node_modules/discord-card-canvas/dist/cards/rating/rank/rank-card.js:318:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RankCardBuilder.build (/home/container/node_modules/discord-card-canvas/dist/cards/rating/rank/rank-card.js:454:9)
    at async module.exports (/home/container/src/commands/levels/rank3.js:38:20)```

**Comment by Gusarovv** [comment]
Hmm, thanks @brdser 
Can you please send the URL of this avatar? Are you using the latest version of the package?

**Comment by brddev** [comment]
Ys, am using latest version of code and i have consoled the Avatar url and i gets this
https://cdn.discordapp.com/avatars/870596321508208680/ab1a5744b2bf8ee6b19c6d7ccd41c6a2.webp
 Error: Error loading the avatar image. The URL may be invalid. at RankCardBuilder.draw (/home/container/node_modules/disc ord-card-canvas/dist/cards/rating/rank/rank-card.js:318:27) at runMicrotasks (<anonymous>>

at processTicksAndRejections (node:internal/process/task_queues:96;5)

at async RankCardBuilder.build (/home/container/node_modules/discord-card-canvas/dist/cards/rating/rank/rank-card.js:454:9)

at async module.exports (/home/container/src/commands/leve 1s/rank3.js:38:20)

**Comment by rhobales** [comment]
Any solutions here? I'm stuck with the same problem.

**Comment by Gusarovv** [comment]
@rhobales @brddev 

The problem is that canvas does not support images in the '.webp' format. In this format, you are most likely trying to use the image in the `RankCardBuilder'. Check that your application is working correctly. For a better understanding, here is a valid example:
```ts
        const canvasRank = await new RankCardBuilder({
            currentLvl: 102,
            currentRank: 563,
            currentXP: 71032,
            requiredXP: 95195,
            backgroundColor: { background: '#070d19', bubbles: '#0ca7ff' },
            avatarImgURL: interaction.user.displayAvatarURL({ extension: 'png' }), // THIS
            nicknameText: { content: 'xNinja_Catx', font: 'Nunito', color: '#0CA7FF' },
            userStatus: 'idle',
        }).build();
```
